# Generated by Django 5.2 on 2026-08-12 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='账单编号')),
                ('billing_period_start', models.DateField(verbose_name='计费期开始')),
                ('billing_period_end', models.DateField(verbose_name='计费期结束')),
                ('previous_reading', models.FloatField(verbose_name='上次读数')),
                ('current_reading', models.FloatField(verbose_name='本次读数')),
                ('usage', models.FloatField(verbose_name='用水量(m³)')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='基础水费')),
                ('tier_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='阶梯水费')),
                ('tax_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='税费')),
                ('subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='补贴金额')),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='应缴总额')),
                ('paid_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已缴金额')),
                ('status', models.CharField(choices=[('pending', '待缴费'), ('partial', '部分缴费'), ('paid', '已缴费'), ('overdue', '已逾期'), ('waived', '已减免')], default='pending', max_length=20, verbose_name='缴费状态')),
                ('due_date', models.DateField(verbose_name='缴费截止日期')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='缴费时间')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '水费账单',
                'verbose_name_plural': '水费账单管理',
                'ordering': ['-billing_period_end'],
            },
        ),
        migrations.CreateModel(
            name='WaterPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='缴费编号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='缴费金额')),
                ('payment_method', models.CharField(choices=[('cash', '现金'), ('bank_transfer', '银行转账'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('bank_card', '银行卡')], max_length=20, verbose_name='缴费方式')),
                ('payment_time', models.DateTimeField(verbose_name='缴费时间')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='交易流水号')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='water_price.waterbill', verbose_name='账单')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '缴费记录',
                'verbose_name_plural': '缴费记录',
                'ordering': ['-payment_time'],
            },
        ),
        migrations.CreateModel(
            name='WaterPricePolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='政策编号')),
                ('name', models.CharField(max_length=200, verbose_name='政策名称')),
                ('policy_type', models.CharField(choices=[('domestic', '居民生活用水'), ('agriculture', '农业用水'), ('industry', '工业用水'), ('commercial', '商业用水'), ('special', '特种用水')], max_length=20, verbose_name='用水类型')),
                ('pricing_mode', models.CharField(choices=[('flat', '单一水价'), ('阶梯', '阶梯水价'), ('seasonal', '季节性水价'), ('comprehensive', '综合计价')], default='flat', max_length=20, verbose_name='计价模式')),
                ('start_date', models.DateField(verbose_name='生效日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('base_price', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='基础水价(元/m³)')),
                ('tiers', models.JSONField(default=list, verbose_name='阶梯价配置')),
                ('subsidies', models.JSONField(default=list, verbose_name='补贴配置')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='税率(%)')),
                ('description', models.TextField(blank=True, verbose_name='政策说明')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.regionmodel', verbose_name='适用区域')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '水价政策',
                'verbose_name_plural': '水价政策管理',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='waterbill',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='water_price.waterpricepolicy', verbose_name='水价政策'),
        ),
        migrations.CreateModel(
            name='WaterUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='用户编号')),
                ('name', models.CharField(max_length=200, verbose_name='用户名称')),
                ('user_type', models.CharField(choices=[('agriculture', '农业用水户'), ('industrial', '工业用水户'), ('commercial', '商业用水户'), ('domestic', '居民用户'), ('public', '公共设施')], max_length=20, verbose_name='用户类型')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('water_meter', models.CharField(blank=True, max_length=50, verbose_name='水表编号')),
                ('contract_info', models.JSONField(default=dict, verbose_name='合同信息')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否正常')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='water_price.waterpricepolicy', verbose_name='适用水价政策')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.regionmodel', verbose_name='所属区域')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '用水户',
                'verbose_name_plural': '用水户管理',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='waterbill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='water_price.wateruser', verbose_name='用水户'),
        ),
    ]
