# Generated by Django 5.2 on 2026-08-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='设备编码')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('gate', '闸门'), ('pump', '水泵'), ('valve', '阀门'), ('drip_control', '滴灌控制器'), ('sprinkler', '喷灌设备'), ('sensor', '传感器组')], max_length=20, verbose_name='设备类型')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='安装位置')),
                ('device_model', models.CharField(blank=True, max_length=100, verbose_name='设备型号')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='制造商')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='安装日期')),
                ('control_mode', models.CharField(choices=[('manual', '手动'), ('auto', '自动'), ('smart', '智能')], default='auto', max_length=10, verbose_name='控制模式')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('running', '运行中'), ('stopped', '已停止'), ('fault', '故障'), ('maintenance', '维护中')], default='offline', max_length=20, verbose_name='运行状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('params', models.JSONField(default=dict, verbose_name='设备参数')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '灌溉设备',
                'verbose_name_plural': '灌溉设备管理',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('action', models.CharField(max_length=50, verbose_name='操作动作')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='操作值')),
                ('operate_time', models.DateTimeField(verbose_name='操作时间')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时')], default='success', max_length=20, verbose_name='执行结果')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '灌溉操作日志',
                'verbose_name_plural': '灌溉操作日志',
                'ordering': ['-operate_time'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='计划编号')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('plan_type', models.CharField(choices=[('schedule', '定时灌溉'), ('trigger', '触发灌溉'), ('manual', '手动灌溉'), ('smart', '智能灌溉')], default='smart', max_length=20, verbose_name='计划类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='灌溉时长(分钟)')),
                ('flow_rate', models.FloatField(blank=True, null=True, verbose_name='目标流量(m³/s)')),
                ('total_water', models.FloatField(blank=True, null=True, verbose_name='目标水量(m³)')),
                ('trigger_conditions', models.JSONField(default=list, verbose_name='触发条件')),
                ('control_params', models.JSONField(default=dict, verbose_name='控制参数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '执行中'), ('paused', '已暂停'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '灌溉计划',
                'verbose_name_plural': '灌溉计划管理',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='灌溉时长(分钟)')),
                ('water_used', models.FloatField(blank=True, null=True, verbose_name='用水量(m³)')),
                ('energy_used', models.FloatField(blank=True, null=True, verbose_name='用电量(kWh)')),
                ('area_irrigated', models.FloatField(blank=True, null=True, verbose_name='灌溉面积(亩)')),
                ('avg_flow_rate', models.FloatField(blank=True, null=True, verbose_name='平均流量(m³/s)')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '灌溉记录',
                'verbose_name_plural': '灌溉记录',
                'ordering': ['-start_time'],
            },
        ),
    ]
