# Generated by Django 5.2 on 2026-08-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('config_type', models.CharField(choices=[('system', '系统配置'), ('water', '水文配置'), ('device', '设备配置'), ('notification', '通知配置'), ('ai', 'AI配置')], max_length=20, verbose_name='配置类型')),
                ('config_key', models.CharField(max_length=100, verbose_name='配置键')),
                ('config_value', models.JSONField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
            ],
            options={
                'verbose_name': '公共配置',
                'verbose_name_plural': '公共配置管理',
            },
        ),
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('region_type', models.CharField(choices=[('area', '灌区'), ('branch', '干支渠'), ('canal', '斗农渠'), ('section', '渠段'), ('pump_station', '泵站'), ('gate', '闸门'), ('reservoir', '水库')], max_length=20, verbose_name='区域类型')),
                ('geometry', models.JSONField(blank=True, null=True, verbose_name='地理坐标')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '灌区区域',
                'verbose_name_plural': '灌区区域管理',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
