# Generated by Django 5.2 on 2026-08-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiAssistantConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('local', '本地模型'), ('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('qwen', '阿里云百炼'), ('doubao', '豆包'), ('deepseek', 'DeepSeek'), ('ollama', 'Ollama')], default='local', max_length=20, verbose_name='服务商')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('api_url', models.CharField(blank=True, max_length=500, verbose_name='API地址')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API密钥')),
                ('system_prompt', models.TextField(blank=True, verbose_name='系统提示词')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度(0-1)')),
                ('max_tokens', models.IntegerField(default=2048, verbose_name='最大Token数')),
                ('max_history', models.IntegerField(default=10, verbose_name='最大历史对话数')),
                ('timeout', models.IntegerField(default=30, verbose_name='超时时间(秒)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name': 'AI助手配置',
                'verbose_name_plural': 'AI助手配置管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('role', models.CharField(choices=[('system', '系统'), ('user', '用户'), ('assistant', 'AI助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('token_count', models.IntegerField(default=0, verbose_name='Token数量')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='响应时间(秒)')),
                ('source_documents', models.JSONField(default=list, verbose_name='引用文档')),
                ('is_streamed', models.BooleanField(default=False, verbose_name='是否流式输出')),
            ],
            options={
                'verbose_name': 'AI对话消息',
                'verbose_name_plural': 'AI对话消息',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiChatSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='会话标题')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('last_message_time', models.DateTimeField(blank=True, null=True, verbose_name='最后消息时间')),
            ],
            options={
                'verbose_name': 'AI会话',
                'verbose_name_plural': 'AI会话管理',
                'ordering': ['-last_message_time'],
            },
        ),
        migrations.CreateModel(
            name='AiKnowledge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('knowledge_type', models.CharField(choices=[('document', '文档'), ('qa', '问答对'), ('faq', '常见问题'), ('procedure', '操作流程'), ('policy', '政策制度')], default='document', max_length=20, verbose_name='知识类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='摘要')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='向量嵌入')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
