# Generated by Django 5.1.15 on 2026-08-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_aitoollog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aitoollog',
            new_name='ai_assistan_tool_na_600bb9_idx',
            old_name='ai_tool_log_tool_5b7b4d_idx',
        ),
        migrations.RenameIndex(
            model_name='aitoollog',
            new_name='ai_assistan_user_id_d16f65_idx',
            old_name='ai_tool_log_user_0e5908_idx',
        ),
    ]
