# Generated by Django 5.1.15 on 2026-08-17 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_rag_documents_and_memory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ai_knowledge/%Y%m%d/', verbose_name='源文件'),
        ),
        migrations.AlterField(
            model_name='aiknowledgedocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aiknowledgedocument',
            name='source_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='导入源路径'),
        ),
        migrations.AlterField(
            model_name='aiknowledgedocument',
            name='source_type',
            field=models.CharField(default='txt', max_length=30, verbose_name='源文件类型'),
        ),
    ]
