import request from '@/utils/request'

export const login = (data) => request.post('/auth/login/', data)
export const register = (data) => request.post('/auth/register/', data)
export const getCurrentUser = () => request.get('/auth/me/')
export const changePassword = (data) => request.post('/auth/change-password/', data)
export const logout = (data) => request.post('/auth/logout/', data)
export const refreshToken = (data) => request.post('/auth/refresh/', data)

export const getUserList = (params) => request.get('/users/', { params })
export const createUser = (data) => request.post('/users/', data)
export const updateUser = (id, data) => request.put(`/users/${id}/`, data)
export const deleteUser = (id) => request.delete(`/users/${id}/`)
export const getOperationLogs = (params) => request.get('/logs/', { params })

export const getRegions = (params) => request.get('/common/regions/', { params })
export const getRegionTree = () => request.get('/common/regions/tree/')
export const getConfigs = (params) => request.get('/common/configs/', { params })

export const getInspections = (params) => request.get('/inspection/inspections/', { params })
export const createInspection = (data) => request.post('/inspection/inspections/', data)
export const updateInspection = (id, data) => request.put(`/inspection/inspections/${id}/`, data)
export const startInspection = (id) => request.post(`/inspection/inspections/${id}/start/`)
export const completeInspection = (id, data) => request.post(`/inspection/inspections/${id}/complete/`, data)
export const cancelInspection = (id, data) => request.post(`/inspection/inspections/${id}/cancel/`, data)
export const getInspectionStats = () => request.get('/inspection/inspections/statistics/')

export const getWorkOrders = (params) => request.get('/inspection/work-orders/', { params })
export const createWorkOrder = (data) => request.post('/inspection/work-orders/', data)
export const assignWorkOrder = (id, data) => request.post(`/inspection/work-orders/${id}/assign/`, data)
export const startWorkOrder = (id, data) => request.post(`/inspection/work-orders/${id}/start/`, data)
export const completeWorkOrder = (id, data) => request.post(`/inspection/work-orders/${id}/complete/`, data)
export const verifyWorkOrder = (id, data) => request.post(`/inspection/work-orders/${id}/verify/`, data)
export const closeWorkOrder = (id) => request.post(`/inspection/work-orders/${id}/close/`)
export const getWorkOrderStats = () => request.get('/inspection/work-orders/statistics/')

export const getMeasureStations = (params) => request.get('/water-measurement/stations/', { params })
export const getMeasurements = (params) => request.get('/water-measurement/measurements/', { params })
export const getRealtimeMeasurements = (params) => request.get('/water-measurement/measurements/realtime/', { params })
export const getWaterAlarms = (params) => request.get('/water-measurement/alarms/', { params })
export const resolveAlarm = (id, data) => request.post(`/water-measurement/alarms/${id}/resolve/`, data)
export const getWaterStats = () => request.get('/water-measurement/measurements/statistics/')

export const getIrrigationDevices = (params) => request.get('/smart-irrigation/devices/', { params })
export const controlDevice = (id, data) => request.post(`/smart-irrigation/devices/${id}/control/`, data)
export const getIrrigationPlans = (params) => request.get('/smart-irrigation/plans/', { params })
export const createIrrigationPlan = (data) => request.post('/smart-irrigation/plans/', data)
export const getIrrigationRecords = (params) => request.get('/smart-irrigation/records/', { params })
export const getIrrigationStats = () => request.get('/smart-irrigation/records/statistics/')

export const getWaterSources = (params) => request.get('/water-allocation/sources/', { params })
export const getWaterAllocations = (params) => request.get('/water-allocation/allocations/', { params })
export const createWaterAllocation = (data) => request.post('/water-allocation/allocations/', data)
export const getWaterTransfers = (params) => request.get('/water-allocation/transfers/', { params })
export const getAllocationStats = () => request.get('/water-allocation/allocations/statistics/')

export const getWaterPolicies = (params) => request.get('/water-price/policies/', { params })
export const getWaterUsers = (params) => request.get('/water-price/users/', { params })
export const getWaterBills = (params) => request.get('/water-price/bills/', { params })
export const generateBills = (data) => request.post('/water-price/bills/generate/', data)
export const createPayment = (data) => request.post('/water-price/payments/', data)
export const getPriceStats = () => request.get('/water-price/bills/statistics/')

export const getNotices = (params) => request.get('/daily/notices/', { params })
export const publishNotice = (id) => request.post(`/daily/notices/${id}/publish/`)
export const getMeetings = (params) => request.get('/daily/meetings/', { params })
export const getAssets = (params) => request.get('/daily/assets/', { params })
export const getDocuments = (params) => request.get('/daily/documents/', { params })

export const getSoilStations = (params) => request.get('/soil-weather/stations/', { params })
export const getSoilData = (params) => request.get('/soil-weather/soil-data/', { params })
export const getWeatherData = (params) => request.get('/soil-weather/weather-data/', { params })
export const getSoilForecasts = (params) => request.get('/soil-weather/forecasts/', { params })
export const generateForecast = (data) => request.post('/soil-weather/forecasts/generate/', data)
export const getSoilOverview = () => request.get('/soil-weather/forecasts/overview/')

export const sendAiMessage = (data) => request.post('/ai/chat/send/', data)
export const sendAiAgentMessage = (data) => request.post('/ai/chat/agent/', data)
export const getAiSessions = () => request.get('/ai/chat/sessions/')
export const getAiHistory = (sessionId) => request.get('/ai/chat/history/', { params: { session_id: sessionId } })
export const createAiSession = () => request.post('/ai/chat/new-session/')
export const deleteAiSession = (sessionId) => request.delete('/ai/chat/session/', { params: { session_id: sessionId } })
export const getAiConfigs = (params) => request.get('/ai/configs/', { params })
export const getAiKnowledge = (params) => request.get('/ai/knowledge/', { params })
export const uploadAiKnowledge = (formData) => request.post('/ai/knowledge/upload/', formData, {
  headers: { 'Content-Type': 'multipart/form-data' },
})
export const getAiKnowledgeDocuments = () => request.get('/ai/knowledge/documents/')
export const getAiTools = () => request.get('/ai/tools/')
export const getAiToolLogs = (params) => request.get('/ai/chat/tool-logs/', { params })
