# Generated by Django 5.2 on 2026-08-12 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureStation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='测站编码')),
                ('name', models.CharField(max_length=100, verbose_name='测站名称')),
                ('station_type', models.CharField(choices=[('flow', '流量站'), ('water_level', '水位站'), ('quality', '水质站'), ('multifunction', '多功能站')], max_length=20, verbose_name='测站类型')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='具体位置')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('elevation', models.FloatField(blank=True, null=True, verbose_name='海拔(m)')),
                ('communication', models.CharField(choices=[('gprs', 'GPRS'), ('4g', '4G'), ('lora', 'LoRa'), ('ethernet', '以太网'), ('manual', '人工录入')], default='4g', max_length=20, verbose_name='通讯方式')),
                ('device_code', models.CharField(blank=True, max_length=50, verbose_name='设备编号')),
                ('device_model', models.CharField(blank=True, max_length=100, verbose_name='设备型号')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='安装日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_data_time', models.DateTimeField(blank=True, null=True, verbose_name='最后数据时间')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('fault', '故障'), ('maintenance', '维护中')], default='offline', max_length=20, verbose_name='运行状态')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measure_stations', to='common.regionmodel', verbose_name='所属区域')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '量测水测站',
                'verbose_name_plural': '量测水测站管理',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WaterAlarm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('alarm_type', models.CharField(choices=[('flow_high', '流量过高'), ('flow_low', '流量过低'), ('level_high', '水位过高'), ('level_low', '水位过低'), ('quality_abnormal', '水质异常'), ('station_offline', '测站离线'), ('device_fault', '设备故障')], max_length=30, verbose_name='告警类型')),
                ('level', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重'), ('emergency', '紧急')], default='warning', max_length=20, verbose_name='告警级别')),
                ('title', models.CharField(max_length=200, verbose_name='告警标题')),
                ('message', models.TextField(verbose_name='告警描述')),
                ('threshold', models.JSONField(blank=True, null=True, verbose_name='阈值配置')),
                ('current_value', models.FloatField(blank=True, null=True, verbose_name='当前值')),
                ('triggered_at', models.DateTimeField(verbose_name='触发时间')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolution', models.TextField(blank=True, verbose_name='处理说明')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='water_measurement.measurestation', verbose_name='测站')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '水量告警',
                'verbose_name_plural': '水量告警管理',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterMeasurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('measure_time', models.DateTimeField(verbose_name='测量时间')),
                ('flow_rate', models.FloatField(blank=True, null=True, verbose_name='瞬时流量(m³/s)')),
                ('water_level', models.FloatField(blank=True, null=True, verbose_name='水位(m)')),
                ('total_flow', models.FloatField(blank=True, null=True, verbose_name='累计流量(m³)')),
                ('velocity', models.FloatField(blank=True, null=True, verbose_name='流速(m/s)')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='过水面积(m²)')),
                ('water_quality', models.FloatField(blank=True, null=True, verbose_name='水质等级')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='水温(℃)')),
                ('ph', models.FloatField(blank=True, null=True, verbose_name='pH值')),
                ('conductivity', models.FloatField(blank=True, null=True, verbose_name='电导率(μS/cm)')),
                ('turbidity', models.FloatField(blank=True, null=True, verbose_name='浊度(NTU)')),
                ('source', models.CharField(choices=[('auto', '自动采集'), ('manual', '人工录入'), ('import', '批量导入')], default='auto', max_length=20, verbose_name='数据来源')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否异常')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='water_measurement.measurestation', verbose_name='测站')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '量测水数据',
                'verbose_name_plural': '量测水数据',
                'ordering': ['-measure_time'],
                'indexes': [models.Index(fields=['station', '-measure_time'], name='water_measu_station_86ff85_idx'), models.Index(fields=['-measure_time'], name='water_measu_measure_cf2938_idx')],
            },
        ),
    ]
