# Generated by Django 5.2 on 2026-08-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('measure_time', models.DateTimeField(verbose_name='测量时间')),
                ('soil_moisture_0_10', models.FloatField(blank=True, null=True, verbose_name='0-10cm含水率(%)')),
                ('soil_moisture_10_20', models.FloatField(blank=True, null=True, verbose_name='10-20cm含水率(%)')),
                ('soil_moisture_20_40', models.FloatField(blank=True, null=True, verbose_name='20-40cm含水率(%)')),
                ('soil_moisture_40_60', models.FloatField(blank=True, null=True, verbose_name='40-60cm含水率(%)')),
                ('soil_moisture_avg', models.FloatField(blank=True, null=True, verbose_name='平均含水率(%)')),
                ('soil_temperature_10', models.FloatField(blank=True, null=True, verbose_name='10cm地温(℃)')),
                ('soil_temperature_20', models.FloatField(blank=True, null=True, verbose_name='20cm地温(℃)')),
                ('soil_salinity', models.FloatField(blank=True, null=True, verbose_name='土壤盐度(dS/m)')),
                ('soil_ph', models.FloatField(blank=True, null=True, verbose_name='土壤pH值')),
                ('source', models.CharField(default='auto', max_length=20, verbose_name='数据来源')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否异常')),
            ],
            options={
                'verbose_name': '墒情数据',
                'verbose_name_plural': '墒情数据',
                'ordering': ['-measure_time'],
            },
        ),
        migrations.CreateModel(
            name='SoilForecast',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('forecast_type', models.CharField(choices=[('drought', '干旱预警'), ('waterlogging', '涝渍预警'), ('optimal', '适宜状态')], max_length=20, verbose_name='预报类型')),
                ('forecast_time', models.DateTimeField(verbose_name='预报时间')),
                ('forecast_hours', models.IntegerField(default=24, verbose_name='预报时长(小时)')),
                ('current_moisture', models.FloatField(blank=True, null=True, verbose_name='当前含水率(%)')),
                ('predicted_moisture', models.FloatField(blank=True, null=True, verbose_name='预测含水率(%)')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险'), ('critical', '极高风险')], default='low', max_length=20, verbose_name='风险等级')),
                ('advice', models.TextField(blank=True, verbose_name='建议措施')),
                ('trigger_value', models.JSONField(blank=True, null=True, verbose_name='触发指标')),
            ],
            options={
                'verbose_name': '墒情预报',
                'verbose_name_plural': '墒情预报管理',
                'ordering': ['-forecast_time'],
            },
        ),
        migrations.CreateModel(
            name='SoilMonitorStation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='测站编码')),
                ('name', models.CharField(max_length=100, verbose_name='测站名称')),
                ('station_type', models.CharField(choices=[('soil', '墒情监测站'), ('weather', '气象监测站'), ('comprehensive', '综合监测站')], default='comprehensive', max_length=20, verbose_name='测站类型')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='具体位置')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('soil_type', models.CharField(blank=True, max_length=50, verbose_name='土壤类型')),
                ('crop_type', models.CharField(blank=True, max_length=50, verbose_name='主要作物')),
                ('device_code', models.CharField(blank=True, max_length=50, verbose_name='设备编号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_data_time', models.DateTimeField(blank=True, null=True, verbose_name='最后数据时间')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('fault', '故障')], default='offline', max_length=20, verbose_name='运行状态')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '墒情气象测站',
                'verbose_name_plural': '墒情气象测站管理',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('measure_time', models.DateTimeField(verbose_name='测量时间')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='气温(℃)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='相对湿度(%)')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='大气压(hPa)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='风速(m/s)')),
                ('wind_direction', models.CharField(blank=True, max_length=10, verbose_name='风向')),
                ('rainfall', models.FloatField(blank=True, null=True, verbose_name='降水量(mm)')),
                ('solar_radiation', models.FloatField(blank=True, null=True, verbose_name='太阳辐射(W/m²)')),
                ('evapotranspiration', models.FloatField(blank=True, null=True, verbose_name='蒸发量(mm)')),
                ('source', models.CharField(default='auto', max_length=20, verbose_name='数据来源')),
            ],
            options={
                'verbose_name': '气象数据',
                'verbose_name_plural': '气象数据',
                'ordering': ['-measure_time'],
            },
        ),
    ]
