# Generated by Django 5.2 on 2026-08-12 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分配方案编号')),
                ('name', models.CharField(max_length=200, verbose_name='方案名称')),
                ('allocation_type', models.CharField(choices=[('yearly', '年度分配'), ('quarterly', '季度分配'), ('monthly', '月度分配'), ('emergency', '应急调度')], default='yearly', max_length=30, verbose_name='分配类型')),
                ('total_amount', models.FloatField(verbose_name='分配总量(万m³)')),
                ('period_start', models.DateField(verbose_name='生效开始日期')),
                ('period_end', models.DateField(verbose_name='生效结束日期')),
                ('priority', models.IntegerField(default=5, verbose_name='优先级(1-10)')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审批'), ('rejected', '已驳回'), ('executing', '执行中'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('basis', models.TextField(blank=True, verbose_name='分配依据')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '水资源分配方案',
                'verbose_name_plural': '水资源分配方案管理',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='WaterAllocationDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('water_user', models.CharField(max_length=200, verbose_name='用水户/部门')),
                ('user_type', models.CharField(choices=[('agriculture', '农业'), ('industry', '工业'), ('domestic', '生活'), ('ecology', '生态')], default='agriculture', max_length=20, verbose_name='用水类型')),
                ('allocated_amount', models.FloatField(verbose_name='分配水量(万m³)')),
                ('used_amount', models.FloatField(default=0, verbose_name='已用水量(万m³)')),
                ('surplus', models.FloatField(default=0, verbose_name='剩余水量(万m³)')),
                ('ratio', models.FloatField(default=0, verbose_name='分配比例(%)')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='water_allocation.waterallocation', verbose_name='分配方案')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.regionmodel', verbose_name='用水区域')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '分配明细',
                'verbose_name_plural': '分配明细',
                'ordering': ['-allocated_amount'],
            },
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='水源编码')),
                ('name', models.CharField(max_length=100, verbose_name='水源名称')),
                ('source_type', models.CharField(choices=[('reservoir', '水库'), ('river', '河流'), ('groundwater', '地下水'), ('canal', '引水渠'), ('recycled', '再生水')], max_length=20, verbose_name='水源类型')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='总容量(万m³)')),
                ('current_storage', models.FloatField(blank=True, null=True, verbose_name='当前蓄水量(万m³)')),
                ('available', models.FloatField(blank=True, null=True, verbose_name='可用水量(万m³)')),
                ('annual_supply', models.FloatField(blank=True, null=True, verbose_name='年供水量(万m³)')),
                ('min_guaranteed', models.FloatField(blank=True, null=True, verbose_name='最低保障水位')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.regionmodel', verbose_name='所属区域')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '水源',
                'verbose_name_plural': '水源管理',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='waterallocation',
            name='water_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='water_allocation.watersource', verbose_name='水源'),
        ),
        migrations.CreateModel(
            name='WaterTransfer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='调水编号')),
                ('transfer_type', models.CharField(choices=[('inter_region', '区域间调水'), ('inter_source', '水源间调水'), ('emergency', '应急调水')], max_length=20, verbose_name='调水类型')),
                ('amount', models.FloatField(verbose_name='调水量(万m³)')),
                ('reason', models.TextField(verbose_name='调水原因')),
                ('planned_start', models.DateTimeField(verbose_name='计划开始时间')),
                ('planned_end', models.DateTimeField(verbose_name='计划结束时间')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('status', models.CharField(choices=[('planned', '已计划'), ('approved', '已批准'), ('executing', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='状态')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('from_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from', to='common.regionmodel', verbose_name='调出区域')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行操作人')),
                ('to_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to', to='common.regionmodel', verbose_name='调入区域')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '调水调度',
                'verbose_name_plural': '调水调度管理',
                'ordering': ['-planned_start'],
            },
        ),
    ]
