# Generated by Django 5.2 on 2026-08-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='巡检编号')),
                ('title', models.CharField(max_length=200, verbose_name='巡检标题')),
                ('template_type', models.CharField(choices=[('daily', '日常巡检'), ('weekly', '周巡检'), ('monthly', '月巡检'), ('special', '专项巡检'), ('emergency', '应急巡检')], default='daily', max_length=20, verbose_name='巡检类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=10, verbose_name='优先级')),
                ('planned_start', models.DateTimeField(verbose_name='计划开始时间')),
                ('planned_end', models.DateTimeField(verbose_name='计划结束时间')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('overdue', '已逾期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='巡检说明')),
                ('checklist', models.JSONField(default=list, verbose_name='巡检清单')),
                ('photos', models.JSONField(default=list, verbose_name='照片')),
                ('report', models.TextField(blank=True, verbose_name='巡检报告')),
                ('result', models.CharField(blank=True, choices=[('normal', '正常'), ('abnormal', '异常'), ('need_repair', '需维修')], max_length=20, null=True, verbose_name='巡检结果')),
            ],
            options={
                'verbose_name': '巡检任务',
                'verbose_name_plural': '巡检任务管理',
                'ordering': ['-planned_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('item_name', models.CharField(max_length=200, verbose_name='巡检项')),
                ('item_type', models.CharField(blank=True, max_length=50, verbose_name='巡检项类型')),
                ('result', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常'), ('skip', '跳过')], max_length=20, verbose_name='检查结果')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='检查值')),
                ('standard', models.CharField(blank=True, max_length=255, verbose_name='标准值')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('photos', models.JSONField(default=list, verbose_name='照片')),
            ],
            options={
                'verbose_name': '巡检记录',
                'verbose_name_plural': '巡检记录',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='工单编号')),
                ('title', models.CharField(max_length=200, verbose_name='工单标题')),
                ('order_type', models.CharField(choices=[('inspection_issue', '巡检发现'), ('user_report', '用户上报'), ('device_fault', '设备故障'), ('routine_maintenance', '日常维护'), ('emergency', '应急处置'), ('other', '其他')], default='other', max_length=30, verbose_name='工单类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待受理'), ('assigned', '已派单'), ('in_progress', '处理中'), ('completed', '已完成'), ('verified', '已验收'), ('closed', '已关闭'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='具体位置')),
                ('contact_info', models.CharField(blank=True, max_length=100, verbose_name='联系方式')),
                ('photos', models.JSONField(default=list, verbose_name='问题照片')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='计划开始时间')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='计划完成时间')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间')),
                ('solution', models.TextField(blank=True, verbose_name='解决方案')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='费用')),
                ('result_photos', models.JSONField(default=list, verbose_name='处理后照片')),
                ('satisfaction', models.IntegerField(blank=True, null=True, verbose_name='满意度(1-5)')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('action', models.CharField(choices=[('create', '创建'), ('assign', '派单'), ('start', '开始处理'), ('update', '更新'), ('complete', '完成处理'), ('verify', '验收通过'), ('reject', '驳回'), ('close', '关闭'), ('comment', '备注')], max_length=20, verbose_name='操作')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='新状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('attachments', models.JSONField(default=list, verbose_name='附件')),
            ],
            options={
                'verbose_name': '工单日志',
                'verbose_name_plural': '工单日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
